"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u_2tgd@i&_3_&hvx2sowqe)m*9ia7q4l@wwz9h@f3^wo(7zzs1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_profile',
    'courses',
    'exam',
    'user_payment.apps.UserPaymentConfig',
    'teacher',
    
]

#AUTH_USER_MODEL = 'user_profile.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Настройки для SimpleJWT
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

 

# STRIPE_PUBLIC_KEY_TEST = os.getenv('pk_test_51Q9oeERtJj59Ssmcft8TbRebrFIRhe8djPEGswMwKGM5VvkcAL7SH1LPB33wHBO7PhOew4ndMQFkFuMLpCKzcscL00n0u0Z3KZ')
# STRIPE_SECRET_KEY_TEST = os.getenv('sk_test_51Q9oeERtJj59SsmcnvxZlmIooUKmHRgRc7IVwB7PnLkAt3ZVttnAyIfUSnkRzK0E1DRKhKUELBkARbgQxIqX4xkd00KUx1AcR7')
# STRIPE_WEBHOOK_SECRET_TEST = os.getenv('STRIPE_WEBHOOK_SECRET_TEST')
# PRODUCT_PRICE = os.getenv('PRODUCT_PRICE')

STRIPE_PUBLIC_KEY_TEST='pk_test_51Q9oeERtJj59Ssmcft8TbRebrFIRhe8djPEGswMwKGM5VvkcAL7SH1LPB33wHBO7PhOew4ndMQFkFuMLpCKzcscL00n0u0Z3KZ'
STRIPE_SECRET_KEY_TEST='sk_test_51Q9oeERtJj59SsmcnvxZlmIooUKmHRgRc7IVwB7PnLkAt3ZVttnAyIfUSnkRzK0E1DRKhKUELBkARbgQxIqX4xkd00KUx1AcR7'
STRIPE_WEBHOOK_SECRET_TEST='STRIPE_WEBHOOK_SECRET_TEST'
# PRODUCT_PRICE= 'price_1Q9pqmRtJj59SsmcdpFPW87j'
REDIRECT_DOMAIN = 'http://127.0.0.1:8000'
#LOGIN_REDIRECT_URL = '/'
