# Generated by Django 5.1.1 on 2024-10-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
