# Generated by Django 5.1.2 on 2024-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
