# Generated by Django 5.1.2 on 2024-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_usercourse_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
