# Generated by Django 5.1.2 on 2024-12-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
