# Generated by Django 5.1.1 on 2024-10-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_correct_option_question_option_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
