import { defineStore } from 'pinia';
import { ref } from 'vue';

export type Language = 'en' | 'ru' | 'kk';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.myCourses': 'My Courses',
    'nav.becomeTeacher': 'Become a Teacher',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    
    // Home
    'home.title': 'Learn to Code',
    'home.subtitle': 'Build Your Future',
    'home.description': 'Master programming with interactive courses, hands-on projects, and expert guidance. Start your coding journey today!',
    'home.getStarted': 'Get Started',
    'home.exploreCourses': 'Explore Courses',
    'home.popularCourses': 'Our Popular Courses',
    'home.popularCoursesDescription': 'Choose from our wide range of courses designed by industry experts',
    'home.whyChoose': 'Why Choose Easy Code?',
    'home.feature1Title': 'Expert Instructors',
    'home.feature1Description': 'Learn from industry professionals with years of experience',
    'home.feature2Title': 'Learn at Your Pace',
    'home.feature2Description': 'Flexible schedules that fit your lifestyle',
    'home.feature3Title': 'Get Certified',
    'home.feature3Description': 'Earn certificates upon course completion',
    'home.feature4Title': 'Community Support',
    'home.feature4Description': 'Join a thriving community of learners',
    'home.checkBackSoon': 'Check back soon for new courses!',
    
    // Course
    'course.enrollNow': 'Enroll Now',
    'course.enroll': 'Enroll',
    'course.enrolled': 'You are enrolled in this course',
    'course.checkingEnrollment': 'Checking enrollment...',
    'course.details': 'Details',
    'course.aboutCourse': 'About This Course',
    'course.courseVideos': 'Course Videos',
    'course.courseIncludes': 'Course Includes',
    'course.videoLectures': 'Video lectures',
    'course.downloadableResources': 'Downloadable resources',
    'course.lifetimeAccess': 'Lifetime access',
    'course.certificate': 'Certificate of completion',
    'course.preview': 'Preview',
    'course.takeTest': 'Take Test',
    'course.notFound': 'Course Not Found',
    'course.backToHome': 'Back to Home',
    'course.save': 'Save',
    'course.purchaseToAccess': 'Purchase this course to access all video lectures',
    'course.buy': 'Buy Course',
    
    // Progress
    'progress.yourProgress': 'Your Progress',
    'progress.testsCompleted': 'Tests Completed',
    'progress.passRate': 'Pass Rate',
    'progress.courseCompleted': 'Course Completed!',
    'progress.getCertificate': 'Get Certificate',
    
    // Test
    'test.title': 'Test',
    'test.loading': 'Loading test...',
    'test.alreadyTaken': 'You\'ve already taken this test',
    'test.passed': 'Passed',
    'test.failed': 'Failed',
    'test.retake': 'Retake Test',
    'test.question': 'Question',
    'test.of': 'of',
    'test.previous': 'Previous',
    'test.next': 'Next',
    'test.submit': 'Submit Test',
    'test.congratulations': 'Congratulations!',
    'test.testFailed': 'Test Failed',
    'test.youPassed': 'You passed the test!',
    'test.tryAgain': 'You need 70% to pass. Try again!',
    'test.reviewAnswers': 'Review Your Answers:',
    'test.correct': 'Correct',
    'test.incorrect': 'Incorrect',
    'test.yourAnswer': 'Your answer',
    'test.correctAnswer': 'Correct answer',
    'test.close': 'Close',
    
    // Certificate
    'certificate.title': 'Course Certificate',
    'certificate.generating': 'Generating your certificate...',
    'certificate.congratulations': 'Congratulations!',
    'certificate.completed': 'You have successfully completed',
    'certificate.completionDate': 'Completion Date',
    'certificate.download': 'Download Certificate',
    'certificate.notCompleted': 'Course not completed yet',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.signIn': 'Sign In',
    'auth.username': 'Username',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.welcomeBack': 'Welcome Back',
    'auth.loginSubtitle': 'Sign in to continue your learning journey',
    'auth.usernamePlaceholder': 'Enter your username',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.signUpLink': 'Sign Up',
    'auth.haveAccount': 'Already have an account?',
    'auth.signInLink': 'Sign In',
    'auth.joinCommunity': 'Join Our Community',
    'auth.joinCommunityDescription': 'Start your programming journey with thousands of students worldwide',
    'auth.createAccount': 'Create Account',
    'auth.signupSubtitle': 'Sign up to start learning today',
    'auth.firstNamePlaceholder': 'John',
    'auth.lastNamePlaceholder': 'Doe',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.startLearning': 'Start Learning Today',
    'auth.startLearningDescription': 'Access thousands of courses and enhance your skills',
    
    // My Courses
    'myCourses.title': 'My Courses',
    'myCourses.subtitle': 'Continue your learning journey',
    'myCourses.noCourses': 'No courses yet',
    'myCourses.noCoursesDescription': 'Start learning by enrolling in a course',
    'myCourses.browseCourses': 'Browse Courses',
    'myCourses.continueLearning': 'Continue Learning',
    
    // Payment
    'payment.checkout': 'Checkout',
    'payment.processing': 'Processing payment...',
    'payment.success': 'Payment Successful!',
    'payment.enrolled': 'You have been successfully enrolled in',
    'payment.goToCourse': 'Go to Course',
    'payment.viewMyCourses': 'View My Courses',
    'payment.cancelled': 'Payment Cancelled',
    'payment.notCompleted': 'Your payment was not completed',
    'payment.tryAgain': 'Try Again',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.noData': 'No data available',

    // Profile
    'profile.title': 'My Profile',
    'profile.loading': 'Loading profile...',
    'profile.enrolledCourses': 'Enrolled Courses',
    'profile.certificates': 'Certificates',
    'profile.hoursLearned': 'Hours Learned',

    // Teacher
    'teacher.dashboard': 'Teacher Dashboard',
    'teacher.manageCoursesStudents': 'Manage your courses and students',
    'teacher.comingSoon': 'Teacher Dashboard Coming Soon',
    'teacher.comingSoonDescription': 'We\'re working on bringing you a comprehensive teacher dashboard to manage your courses and students.',
    'teacher.backToHome': 'Back to Home',
    'teacher.myCourses': 'My Courses',
    'teacher.totalStudents': 'Total Students',
    'teacher.totalRevenue': 'Total Revenue',
    'teacher.avgRating': 'Average Rating',
    'teacher.createCourse': 'Create New Course',
    'teacher.editCourse': 'Edit Course',
    'teacher.students': 'Students',
    'teacher.published': 'Published',
    'teacher.draft': 'Draft',

    // Final Test
    'finalTest.title': 'Final Course Exam',
    'finalTest.loading': 'Loading final exam...',
    'finalTest.passingScore': 'Passing Score',
    'finalTest.totalQuestions': 'Total Questions',
    'finalTest.takeFinalExam': 'Take Final Exam',
    'finalTest.congratulations': 'Congratulations!',
    'finalTest.failed': 'Exam Failed',
    'finalTest.passedMessage': 'You have successfully completed the course! You can now download your certificate.',
    'finalTest.failedMessage': 'You need 70% to pass. Review the course materials and try again.',
    'finalTest.completeAllTests': 'Complete all video tests to unlock final exam',

    // Footer
    'footer.title': 'Easy Code',
    'footer.description': 'We offer high-quality online courses in programming and other fields with an intuitive interface, flexible learning schedules, and user support. Learn at your convenience and test your knowledge with interactive quizzes!',
    'footer.quickLinks': 'Quick Links',
    'footer.forTeachers': 'For Teachers',
    'footer.connect': 'Connect With Us',
    'footer.copyright': '© 2024 by Easycode Team. All rights reserved.',
    'course.python-for-beginners.title': 'Python for Beginners',
    'course.python-for-beginners.description': 'Learn Python basics with hands-on exercises and real-world examples. This course covers variables, control flow, functions, and simple projects to build confidence and practical skills.',
    'course.python-for-beginners.summary': 'Start your programming journey with Python fundamentals and practical tasks.',
    'course.python_for_beginners.title': 'Python for Beginners',
    'course.python_for_beginners.description': 'Learn Python basics with hands-on exercises and real-world examples. This course covers variables, control flow, functions, and simple projects to build confidence and practical skills.',
    'course.python_for_beginners.summary': 'Start your programming journey with Python fundamentals and practical tasks.',
    'course.c-for-beginners.title': 'C++ for Beginners',
    'course.c-for-beginners.description': 'Master C++ fundamentals and build efficient applications from scratch. You will explore memory management, object-oriented programming, and standard library tools for real-world development.',
    'course.c-for-beginners.summary': 'Learn the essentials of C++ and begin writing high-performance code.',
    'course.cpp-for-beginners.title': 'C++ for Beginners',
    'course.cpp-for-beginners.description': 'Master C++ fundamentals and build efficient applications from scratch. You will explore memory management, object-oriented programming, and standard library tools for real-world development.',
    'course.cpp-for-beginners.summary': 'Learn the essentials of C++ and begin writing high-performance code.',
    'course.cplusplus_for_beginners.title': 'C++ for Beginners',
    'course.cplusplus_for_beginners.description': 'Master C++ fundamentals and build efficient applications from scratch. You will explore memory management, object-oriented programming, and standard library tools for real-world development.',
    'course.cplusplus_for_beginners.summary': 'Learn the essentials of C++ and begin writing high-performance code.',
    'course.javascript-for-beginners.title': 'JavaScript for Beginners',
    'course.javascript-for-beginners.description': 'Explore JavaScript essentials for interactive web development. You will learn DOM manipulation, events, functions, and modern syntax to build dynamic web pages.',
    'course.javascript-for-beginners.summary': 'Get started with JavaScript and build your first dynamic web pages.',
    'course.javascript_for_beginners.title': 'JavaScript for Beginners',
    'course.javascript_for_beginners.description': 'Explore JavaScript essentials for interactive web development. You will learn DOM manipulation, events, functions, and modern syntax to build dynamic web pages.',
    'course.javascript_for_beginners.summary': 'Get started with JavaScript and build your first dynamic web pages.',
    'course.react-framework.title': 'React Framework',
    'course.react-framework.description': 'Build dynamic user interfaces using React components and hooks. The course walks you through state management, reusable components, and modern UI patterns for scalable applications.',
    'course.react-framework.summary': 'Learn how to create modern front-end apps with React and reusable components.',
    'course.react_framework.title': 'React Framework',
    'course.react_framework.description': 'Build dynamic user interfaces using React components and hooks. The course walks you through state management, reusable components, and modern UI patterns for scalable applications.',
    'course.react_framework.summary': 'Learn how to create modern front-end apps with React and reusable components.',
    'course.vue-js-framework.title': 'Vue JS Framework',
    'course.vue-js-framework.description': 'Create modern web apps using the Vue.js progressive framework. You will learn reactivity, component structure, and how to build maintainable single-page applications.',
    'course.vue-js-framework.summary': 'Learn Vue.js and build reactive apps with clean, simple syntax.',
    'course.vuejs_framework.title': 'Vue JS Framework',
    'course.vuejs_framework.description': 'Create modern web apps using the Vue.js progressive framework. You will learn reactivity, component structure, and how to build maintainable single-page applications.',
    'course.vuejs_framework.summary': 'Learn Vue.js and build reactive apps with clean, simple syntax.',
    'course.unity-development.title': 'Unity Development',
    'course.unity-development.description': 'Learn game development with Unity and build immersive experiences. This course covers scene setup, scripting, physics, and interactive gameplay for real-world projects.',
    'course.unity-development.summary': 'Start building games in Unity with practical tutorials and real projects.',
    'course.unity_development.title': 'Unity Development',
    'course.unity_development.description': 'Learn game development with Unity and build immersive experiences. This course covers scene setup, scripting, physics, and interactive gameplay for real-world projects.',
    'course.unity_development.summary': 'Start building games in Unity with practical tutorials and real projects.',
  },
  ru: {
    // Header
    'nav.home': 'Главная',
    'nav.courses': 'Курсы',
    'nav.myCourses': 'Мои курсы',
    'nav.becomeTeacher': 'Стать преподавателем',
    'nav.profile': 'Профиль',
    'nav.logout': 'Выйти',
    'nav.login': 'Войти',
    'nav.signup': 'Регистрация',
    
    // Home
    'home.title': 'Учись программировать',
    'home.subtitle': 'Построй свое будущее',
    'home.description': 'Освой программирование с интерактивными курсами, практическими проектами и руководством экспертов. Начни свой путь в программировании сегодня!',
    'home.getStarted': 'Начать',
    'home.exploreCourses': 'Изучить курсы',
    'home.popularCourses': 'Наши популярные курсы',
    'home.popularCoursesDescription': 'Выбери из широкого спектра курсов, разработанных экспертами индустрии',
    'home.whyChoose': 'Почему Easy Code?',
    'home.feature1Title': 'Эксперты-преподаватели',
    'home.feature1Description': 'Учись у профессионалов индустрии с многолетним опытом',
    'home.feature2Title': 'Учись в своем темпе',
    'home.feature2Description': 'Гибкий график, который подходит твоему образу жизни',
    'home.feature3Title': 'Получай сертификаты',
    'home.feature3Description': 'Зарабатывай сертификаты после завершения курсов',
    'home.feature4Title': 'Поддержка сообщества',
    'home.feature4Description': 'Присоединяйся к процветающему сообществу учащихся',
    'home.checkBackSoon': 'Скоро появятся новые курсы!',
    
    // Course
    'course.enrollNow': 'Записаться',
    'course.enroll': 'Записаться',
    'course.enrolled': 'Вы записаны на этот курс',
    'course.checkingEnrollment': 'Проверка записи...',
    'course.details': 'Подробнее',
    'course.aboutCourse': 'О курсе',
    'course.courseVideos': 'Видео курса',
    'course.courseIncludes': 'Курс включает',
    'course.videoLectures': 'Видео лекции',
    'course.downloadableResources': 'Загружаемые материалы',
    'course.lifetimeAccess': 'Пожизненный доступ',
    'course.certificate': 'Сертификат о прохождении',
    'course.preview': 'Предпросмотр',
    'course.takeTest': 'Пройти тест',
    'course.notFound': 'Курс не найден',
    'course.backToHome': 'Вернуться на главную',
    'course.save': 'Экономия',
    'course.purchaseToAccess': 'Приобретите этот курс для доступа ко всем видео лекциям',
    'course.buy': 'Купить курс',
    
    // Progress
    'progress.yourProgress': 'Ваш прогресс',
    'progress.testsCompleted': 'Тесты пройдены',
    'progress.passRate': 'Процент успеха',
    'progress.courseCompleted': 'Курс завершен!',
    'progress.getCertificate': 'Получить сертификат',
    
    // Test
    'test.title': 'Тест',
    'test.loading': 'Загрузка теста...',
    'test.alreadyTaken': 'Вы уже проходили этот тест',
    'test.passed': 'Сдан',
    'test.failed': 'Не сдан',
    'test.retake': 'Пересдать',
    'test.question': 'Вопрос',
    'test.of': 'из',
    'test.previous': 'Назад',
    'test.next': 'Далее',
    'test.submit': 'Отправить',
    'test.congratulations': 'Поздравляем!',
    'test.testFailed': 'Тест не сдан',
    'test.youPassed': 'Вы сдали тест!',
    'test.tryAgain': 'Нужно набрать 70% для прохождения. Попробуй еще раз!',
    'test.reviewAnswers': 'Просмотр ваших ответов:',
    'test.correct': 'Правильно',
    'test.incorrect': 'Неправильно',
    'test.yourAnswer': 'Ваш ответ',
    'test.correctAnswer': 'Правильный ответ',
    'test.close': 'Закрыть',
    
    // Certificate
    'certificate.title': 'Сертификат курса',
    'certificate.generating': 'Генерация сертификата...',
    'certificate.congratulations': 'Поздравляем!',
    'certificate.completed': 'Вы успешно завершили',
    'certificate.completionDate': 'Дата завершения',
    'certificate.download': 'Скачать сертификат',
    'certificate.notCompleted': 'Курс еще не завершен',
    
    // Auth
    'auth.login': 'Вход',
    'auth.signup': 'Регистрация',
    'auth.signIn': 'Войти',
    'auth.username': 'Имя пользователя',
    'auth.email': 'Электронная почта',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Подтвердите пароль',
    'auth.firstName': 'Имя',
    'auth.lastName': 'Фамилия',
    'auth.welcomeBack': 'С возвращением',
    'auth.loginSubtitle': 'Войдите, чтобы продолжить обучение',
    'auth.usernamePlaceholder': 'Введите имя пользователя',
    'auth.passwordPlaceholder': 'Введите пароль',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.signUpLink': 'Зарегистрироваться',
    'auth.haveAccount': 'Уже есть аккаунт?',
    'auth.signInLink': 'Войти',
    'auth.joinCommunity': 'Присоединяйся к нашему сообществу',
    'auth.joinCommunityDescription': 'Начни свой путь в программировании с тысячами студентов по всему миру',
    'auth.createAccount': 'Создать аккаунт',
    'auth.signupSubtitle': 'Зарегистрируйтесь, чтобы начать обучение сегодня',
    'auth.firstNamePlaceholder': 'Иван',
    'auth.lastNamePlaceholder': 'Иванов',
    'auth.emailPlaceholder': 'ваш@email.com',
    'auth.confirmPasswordPlaceholder': 'Подтвердите пароль',
    'auth.passwordMismatch': 'Пароли не совпадают',
    'auth.startLearning': 'Начни учиться сегодня',
    'auth.startLearningDescription': 'Получи доступ к тысячам курсов и улучши свои навыки',
    
    // My Courses
    'myCourses.title': 'Мои курсы',
    'myCourses.subtitle': 'Продолжайте свой путь обучения',
    'myCourses.noCourses': 'У вас пока нет курсов',
    'myCourses.noCoursesDescription': 'Начните обучение, записавшись на курс',
    'myCourses.browseCourses': 'Посмотреть курсы',
    'myCourses.continueLearning': 'Продолжить обучение',
    
    // Payment
    'payment.checkout': 'Оформление',
    'payment.processing': 'Обработка платежа...',
    'payment.success': 'Оплата успешна!',
    'payment.enrolled': 'Вы успешно записались на курс',
    'payment.goToCourse': 'Перейти к курсу',
    'payment.viewMyCourses': 'Мои курсы',
    'payment.cancelled': 'Оплата отменена',
    'payment.notCompleted': 'Ваш платеж не был завершен',
    'payment.tryAgain': 'Попробовать снова',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.back': 'Назад',
    'common.continue': 'Продолжить',
    'common.noData': 'Нет данных',

    // Profile
    'profile.title': 'Мой профиль',
    'profile.loading': 'Загрузка профиля...',
    'profile.enrolledCourses': 'Записанных курсов',
    'profile.certificates': 'Сертификаты',
    'profile.hoursLearned': 'Часов обучения',

    // Teacher
    'teacher.dashboard': 'Панель преподавателя',
    'teacher.manageCoursesStudents': 'Управляйте своими курсами и студентами',
    'teacher.comingSoon': 'Панель преподавателя скоро',
    'teacher.comingSoonDescription': 'Мы работаем над созданием комплексной панели преподавателя для управления вашими курсами и студентами.',
    'teacher.backToHome': 'На главную',
    'teacher.myCourses': 'Мои курсы',
    'teacher.totalStudents': 'Всего студентов',
    'teacher.totalRevenue': 'Общий доход',
    'teacher.avgRating': 'Средний рейтинг',
    'teacher.createCourse': 'Создать курс',
    'teacher.editCourse': 'Редактировать курс',
    'teacher.students': 'студентов',
    'teacher.published': 'Опубликован',
    'teacher.draft': 'Черновик',

    // Final Test
    'finalTest.title': 'Финальный экзамен курса',
    'finalTest.loading': 'Загрузка финального экзамена...',
    'finalTest.passingScore': 'Проходной балл',
    'finalTest.totalQuestions': 'Всего вопросов',
    'finalTest.takeFinalExam': 'Пройти финальный экзамен',
    'finalTest.congratulations': 'Поздравляем!',
    'finalTest.failed': 'Экзамен не сдан',
    'finalTest.passedMessage': 'Вы успешно завершили курс! Теперь вы можете скачать свой сертификат.',
    'finalTest.failedMessage': 'Нужно набрать 70% для прохождения. Повторите материалы курса и попробуйте снова.',
    'finalTest.completeAllTests': 'Пройдите все тесты видео, чтобы разблокировать финальный экзамен',

    // Footer
    'footer.title': 'Easy Code',
    'footer.description': 'Мы предлагаем высококачественные онлайн-курсы по программированию и другим областям с интуитивно понятным интерфейсом, гибким графиком обучения и поддержкой пользователей. Учитесь в удобное для вас время и проверяйте свои знания с помощью интерактивных тестов!',
    'footer.quickLinks': 'Быстрые ссылки',
    'footer.forTeachers': 'Для преподавателей',
    'footer.connect': 'Свяжитесь с нами',
    'footer.copyright': '© 2024 команда Easycode. Все права защищены.',
    'course.python-for-beginners.title': 'Python для начинающих',
    'course.python-for-beginners.description': 'Изучите основы Python с практическими упражнениями и реальными примерами. Курс познакомит вас с переменными, условными операторами, функциями и простыми проектами, которые помогут закрепить знания.',
    'course.python-for-beginners.summary': 'Начните изучать программирование с основ Python и практических заданий.',
    'course.python_for_beginners.title': 'Python для начинающих',
    'course.python_for_beginners.description': 'Изучите основы Python с практическими упражнениями и реальными примерами. Курс познакомит вас с переменными, условными операторами, функциями и простыми проектами, которые помогут закрепить знания.',
    'course.python_for_beginners.summary': 'Начните изучать программирование с основ Python и практических заданий.',
    'course.c-for-beginners.title': 'C++ для начинающих',
    'course.c-for-beginners.description': 'Овладейте основами C++ и создавайте эффективные приложения с нуля. Вы изучите управление памятью, объектно-ориентированное программирование и работу с библиотекой STL.',
    'course.c-for-beginners.summary': 'Изучите основы C++ и начните писать высокопроизводительный код.',
    'course.cpp-for-beginners.title': 'C++ для начинающих',
    'course.cpp-for-beginners.description': 'Овладейте основами C++ и создавайте эффективные приложения с нуля. Вы изучите управление памятью, объектно-ориентированное программирование и работу с библиотекой STL.',
    'course.cpp-for-beginners.summary': 'Изучите основы C++ и начните писать высокопроизводительный код.',
    'course.cplusplus_for_beginners.title': 'C++ для начинающих',
    'course.cplusplus_for_beginners.description': 'Овладейте основами C++ и создавайте эффективные приложения с нуля. Вы изучите управление памятью, объектно-ориентированное программирование и работу с библиотекой STL.',
    'course.cplusplus_for_beginners.summary': 'Изучите основы C++ и начните писать высокопроизводительный код.',
    'course.javascript-for-beginners.title': 'JavaScript для начинающих',
    'course.javascript-for-beginners.description': 'Изучите основы JavaScript для интерактивной веб-разработки. Вы узнаете, как работать с DOM, событиями, функциями и современным синтаксисом.',
    'course.javascript-for-beginners.summary': 'Начните с JavaScript и создайте первые динамические страницы.',
    'course.javascript_for_beginners.title': 'JavaScript для начинающих',
    'course.javascript_for_beginners.description': 'Изучите основы JavaScript для интерактивной веб-разработки. Вы узнаете, как работать с DOM, событиями, функциями и современным синтаксисом.',
    'course.javascript_for_beginners.summary': 'Начните с JavaScript и создайте первые динамические страницы.',
    'course.react-framework.title': 'React Framework',
    'course.react-framework.description': 'Создавайте динамичные пользовательские интерфейсы с помощью React. Курс проведёт вас по управлению состоянием, повторно используемым компонентам и современным UI-паттернам.',
    'course.react-framework.summary': 'Научитесь создавать современные фронтенд-приложения с React.',
    'course.react_framework.title': 'React Framework',
    'course.react_framework.description': 'Создавайте динамичные пользовательские интерфейсы с помощью React. Курс проведёт вас по управлению состоянием, повторно используемым компонентам и современным UI-паттернам.',
    'course.react_framework.summary': 'Научитесь создавать современные фронтенд-приложения с React.',
    'course.vue-js-framework.title': 'Vue JS Framework',
    'course.vue-js-framework.description': 'Создавайте современные веб-приложения с прогрессивным фреймворком Vue.js. Вы изучите реактивность, структуру компонентов и создание поддерживаемых SPA.',
    'course.vue-js-framework.summary': 'Изучите Vue.js и создавайте реактивные приложения с простым синтаксисом.',
    'course.vuejs_framework.title': 'Vue JS Framework',
    'course.vuejs_framework.description': 'Создавайте современные веб-приложения с прогрессивным фреймворком Vue.js. Вы изучите реактивность, структуру компонентов и создание поддерживаемых SPA.',
    'course.vuejs_framework.summary': 'Изучите Vue.js и создавайте реактивные приложения с простым синтаксисом.',
    'course.unity-development.title': 'Разработка на Unity',
    'course.unity-development.description': 'Изучите разработку игр на Unity и создавайте захватывающие проекты. Курс охватывает создание сцен, скрипты, физику и разработку игрового процесса.',
    'course.unity-development.summary': 'Начните создавать игры в Unity с практическими уроками и реальными проектами.',
    'course.unity_development.title': 'Разработка на Unity',
    'course.unity_development.description': 'Изучите разработку игр на Unity и создавайте захватывающие проекты. Курс охватывает создание сцен, скрипты, физику и разработку игрового процесса.',
    'course.unity_development.summary': 'Начните создавать игры в Unity с практическими уроками и реальными проектами.',
  },
  kk: {
    // Header
    'nav.home': 'Басты бет',
    'nav.courses': 'Курстар',
    'nav.myCourses': 'Менің курстарым',
    'nav.becomeTeacher': 'Оқытушы болу',
    'nav.profile': 'Профиль',
    'nav.logout': 'Шығу',
    'nav.login': 'Кіру',
    'nav.signup': 'Тіркелу',
    
    // Home
    'home.title': 'Бағдарламалауды үйрен',
    'home.subtitle': 'Болашағыңды құр',
    'home.description': 'Интерактивті курстармен, практикалық жобалармен және сарапшылардың нұсқауларымен бағдарламалауды меңгер. Бүгін бағдарламалау жолыңды бастаңыз!',
    'home.getStarted': 'Бастау',
    'home.exploreCourses': 'Курстарды көру',
    'home.popularCourses': 'Біздің танымал курстар',
    'home.popularCoursesDescription': 'Индустрия сарапшылары әзірлеген курстардың кең ауқымынан таңдаңыз',
    'home.whyChoose': 'Неге Easy Code?',
    'home.feature1Title': 'Білікті оқытушылар',
    'home.feature1Description': 'Көп жылдық тәжірибесі бар индустрия мамандарынан үйреніңіз',
    'home.feature2Title': 'Өз қарқыныңызбен үйреніңіз',
    'home.feature2Description': 'Өмір салтыңызға сәйкес келетін икемді кесте',
    'home.feature3Title': 'Сертификат алыңыз',
    'home.feature3Description': 'Курсты аяқтағаннан кейін сертификат алыңыз',
    'home.feature4Title': 'Қоғамдастық қолдауы',
    'home.feature4Description': 'Өркендеп келе жатқан оқушылар қоғамдастығына қосылыңыз',
    'home.checkBackSoon': 'Жуырда жаңа курстар пайда болады!',
    
    // Course
    'course.enrollNow': 'Тіркелу',
    'course.enroll': 'Тіркелу',
    'course.enrolled': 'Сіз бұл курсқа жазылғансыз',
    'course.checkingEnrollment': 'Тіркелуді тексеру...',
    'course.details': 'Толығырақ',
    'course.aboutCourse': 'Курс туралы',
    'course.courseVideos': 'Курс бейнелері',
    'course.courseIncludes': 'Курс қамтиды',
    'course.videoLectures': 'Бейне дәрістер',
    'course.downloadableResources': 'Жүктелетін материалдар',
    'course.lifetimeAccess': 'Өмір бойы қол жетімділік',
    'course.certificate': 'Аяқтау сертификаты',
    'course.preview': 'Алдын ала қарау',
    'course.takeTest': 'Тест тапсыру',
    'course.notFound': 'Курс табылмады',
    'course.backToHome': 'Басты бетке',
    'course.save': 'Үнемдеу',
    'course.purchaseToAccess': 'Барлық бейне дәрістерге қол жетуге арналған курсты сатып алыңыз',
    'course.buy': 'Курсты сатып алу',
    
    // Progress
    'progress.yourProgress': 'Сіздің прогресс',
    'progress.testsCompleted': 'Тапсырылған тесттер',
    'progress.passRate': 'Табыс пайызы',
    'progress.courseCompleted': 'Курс аяқталды!',
    'progress.getCertificate': 'Сертификат алу',
    
    // Test
    'test.title': 'Тест',
    'test.loading': 'Тест жүктелуде...',
    'test.alreadyTaken': 'Сіз бұл тестті өттіңіз',
    'test.passed': 'Тапсырылды',
    'test.failed': 'Тапсырылмады',
    'test.retake': 'Қайта тапсыру',
    'test.question': 'Сұрақ',
    'test.of': '-ден',
    'test.previous': 'Артқа',
    'test.next': 'Алға',
    'test.submit': 'Жіберу',
    'test.congratulations': 'Құттықтаймыз!',
    'test.testFailed': 'Тест тапсырылмады',
    'test.youPassed': 'Сіз тестті тапсырдыңыз!',
    'test.tryAgain': 'Өту үшін 70% керек. Тағы көріңіз!',
    'test.reviewAnswers': 'Жауаптарыңызды қарау:',
    'test.correct': 'Дұрыс',
    'test.incorrect': 'Қате',
    'test.yourAnswer': 'Сіздің жауабыңыз',
    'test.correctAnswer': 'Дұрыс жауап',
    'test.close': 'Жабу',
    
    // Certificate
    'certificate.title': 'Курс сертификаты',
    'certificate.generating': 'Сертификат жасалуда...',
    'certificate.congratulations': 'Құттықтаймыз!',
    'certificate.completed': 'Сіз сәтті аяқтадыңыз',
    'certificate.completionDate': 'Аяқтау күні',
    'certificate.download': 'Сертификатты жүктеу',
    'certificate.notCompleted': 'Курс әлі аяқталмаған',
    
    // Auth
    'auth.login': 'Кіру',
    'auth.signup': 'Тіркелу',
    'auth.signIn': 'Кіру',
    'auth.username': 'Пайдаланушы аты',
    'auth.email': 'Электрондық пошта',
    'auth.password': 'Құпия сөз',
    'auth.confirmPassword': 'Құпия сөзді растау',
    'auth.firstName': 'Аты',
    'auth.lastName': 'Тегі',
    'auth.welcomeBack': 'Қайта келуіңізбен',
    'auth.loginSubtitle': 'Оқуды жалғастыру үшін кіріңіз',
    'auth.usernamePlaceholder': 'Пайдаланушы атын енгізіңіз',
    'auth.passwordPlaceholder': 'Құпия сөзді енгізіңіз',
    'auth.noAccount': 'Аккаунт жоқ па?',
    'auth.signUpLink': 'Тіркелу',
    'auth.haveAccount': 'Аккаунт бар ма?',
    'auth.signInLink': 'Кіру',
    'auth.joinCommunity': 'Біздің қауымдастыққа қосылыңыз',
    'auth.joinCommunityDescription': 'Бүкіл әлемдегі мыңдаған студенттермен бағдарламалау жолыңызды бастаңыз',
    'auth.createAccount': 'Аккаунт жасау',
    'auth.signupSubtitle': 'Бүгін оқуды бастау үшін тіркеліңіз',
    'auth.firstNamePlaceholder': 'Әлі',
    'auth.lastNamePlaceholder': 'Нұрсұлтан',
    'auth.emailPlaceholder': 'сіздің@email.com',
    'auth.confirmPasswordPlaceholder': 'Құпия сөзді растаңыз',
    'auth.passwordMismatch': 'Құпия сөздер сәйкес келмейді',
    'auth.startLearning': 'Бүгін оқуды бастаңыз',
    'auth.startLearningDescription': 'Мыңдаған курстарға қол жеткізіңіз және дағдыларыңызды жақсартыңыз',
    
    // My Courses
    'myCourses.title': 'Менің курстарым',
    'myCourses.subtitle': 'Оқу жолыңызды жалғастырыңыз',
    'myCourses.noCourses': 'Әлі курстар жоқ',
    'myCourses.noCoursesDescription': 'Курсқа жазылу арқылы оқуды бастаңыз',
    'myCourses.browseCourses': 'Курстарды қарау',
    'myCourses.continueLearning': 'Оқуды жалғастыру',
    
    // Payment
    'payment.checkout': 'Төлем',
    'payment.processing': 'Төлем өңделуде...',
    'payment.success': 'Төлем сәтті!',
    'payment.enrolled': 'Сіз сәтті жазылдыңыз',
    'payment.goToCourse': 'Курсқа өту',
    'payment.viewMyCourses': 'Менің курстарым',
    'payment.cancelled': 'Төлем тоқтатылды',
    'payment.notCompleted': 'Сіздің төлеміңіз аяқталмады',
    'payment.tryAgain': 'Қайталап көріңіз',
    
    // Common
    'common.loading': 'Жүктелуде...',
    'common.error': 'Қате',
    'common.success': 'Сәтті',
    'common.cancel': 'Болдырмау',
    'common.save': 'Сақтау',
    'common.delete': 'Жою',
    'common.edit': 'Өңдеу',
    'common.back': 'Артқа',
    'common.continue': 'Жалғастыру',
    'common.noData': 'Деректер жоқ',

    // Profile
    'profile.title': 'Менің профилім',
    'profile.loading': 'Профиль жүктелуде...',
    'profile.enrolledCourses': 'Тіркелген курстар',
    'profile.certificates': 'Сертификаттар',
    'profile.hoursLearned': 'Оқу сағаттары',

    // Teacher
    'teacher.dashboard': 'Оқытушы панелі',
    'teacher.manageCoursesStudents': 'Курстар мен студенттерді басқару',
    'teacher.comingSoon': 'Оқытушы панелі жақында',
    'teacher.comingSoonDescription': 'Біз курстар мен студенттерді басқаруға арналған толық оқытушы панелін жасаудамыз.',
    'teacher.backToHome': 'Басты бетке',
    'teacher.myCourses': 'Менің курстарым',
    'teacher.totalStudents': 'Барлық студенттер',
    'teacher.totalRevenue': 'Жалпы кіріс',
    'teacher.avgRating': 'Орташа рейтинг',
    'teacher.createCourse': 'Курс жасау',
    'teacher.editCourse': 'Курсты өңдеу',
    'teacher.students': 'студенттер',
    'teacher.published': 'Жарияланған',
    'teacher.draft': 'Жоба',

    // Final Test
    'finalTest.title': 'Курстың қорытынды емтиханы',
    'finalTest.loading': 'Қорытынды емтихан жүктелуде...',
    'finalTest.passingScore': 'Өту балы',
    'finalTest.totalQuestions': 'Барлық сұрақтар',
    'finalTest.takeFinalExam': 'Қорытынды емтихан тапсыру',
    'finalTest.congratulations': 'Құттықтаймыз!',
    'finalTest.failed': 'Емтихан тапсырылмады',
    'finalTest.passedMessage': 'Сіз курсты сәтті аяқтадыңыз! Енді сертификатты жүктеп алуға болады.',
    'finalTest.failedMessage': 'Өту үшін 70% жинау керек. Курс материалдарын қайталап, қайтадан көріңіз.',
    'finalTest.completeAllTests': 'Қорытынды емтиханды ашу үшін барлық видео тесттерін аяқтаңыз',

    // Footer
    'footer.title': 'Easy Code',
    'footer.description': 'Біз интуитивті интерфейспен, икемді оқу кестесімен және пайдаланушыларды қолдаумен бағдарламалау және басқа салаларда жоғары сапалы онлайн курстарды ұсынамыз. Өзіңізге ыңғайлы уақытта оқып, интерактивті тесттермен білімді тексеріңіз!',
    'footer.quickLinks': 'Жылдам сілтемелер',
    'footer.forTeachers': 'Оқытушыларға',
    'footer.connect': 'Бізбен байланысыңыз',
    'footer.copyright': '© 2024 Easycode тобы. Барлық құқықтар қорғалған.',
    'course.python-for-beginners.title': 'Python бастаушыларға',
    'course.python-for-beginners.description': 'Практикалық жаттығулар мен нақты мысалдар арқылы Python негіздерін меңгеріңіз. Курс айнымалылар, шартты операторлар, функциялар және қарапайым жобалар арқылы білімді тереңдетеді.',
    'course.python-for-beginners.summary': 'Python негіздерімен танысып, практикалық тапсырмаларды орындаңыз.',
    'course.python_for_beginners.title': 'Python бастаушыларға',
    'course.python_for_beginners.description': 'Практикалық жаттығулар мен нақты мысалдар арқылы Python негіздерін меңгеріңіз. Курс айнымалылар, шартты операторлар, функциялар және қарапайым жобалар арқылы білімді тереңдетеді.',
    'course.python_for_beginners.summary': 'Python негіздерімен танысып, практикалық тапсырмаларды орындаңыз.',
    'course.c-for-beginners.title': 'C++ бастаушыларға',
    'course.c-for-beginners.description': 'C++ негіздерін меңгеріп, тиімді қосымшаларды нөлден жасаңыз. Сіз жадты басқару, объектіге бағытталған бағдарлау және STL кітапханасын қолдану жолдарын үйренесіз.',
    'course.c-for-beginners.summary': 'C++ негіздерін үйреніп, жоғары өнімді код жазуды бастаңыз.',
    'course.cpp-for-beginners.title': 'C++ бастаушыларға',
    'course.cpp-for-beginners.description': 'C++ негіздерін меңгеріп, тиімді қосымшаларды нөлден жасаңыз. Сіз жадты басқару, объектіге бағытталған бағдарлау және STL кітапханасын қолдану жолдарын үйренесіз.',
    'course.cpp-for-beginners.summary': 'C++ негіздерін үйреніп, жоғары өнімді код жазуды бастаңыз.',
    'course.cplusplus_for_beginners.title': 'C++ бастаушыларға',
    'course.cplusplus_for_beginners.description': 'C++ негіздерін меңгеріп, тиімді қосымшаларды нөлден жасаңыз. Сіз жадты басқару, объектіге бағытталған бағдарлау және STL кітапханасын қолдану жолдарын үйренесіз.',
    'course.cplusplus_for_beginners.summary': 'C++ негіздерін үйреніп, жоғары өнімді код жазуды бастаңыз.',
    'course.javascript-for-beginners.title': 'JavaScript бастаушыларға',
    'course.javascript-for-beginners.description': 'Интерактивті веб-дамытуды үйрену үшін JavaScript негіздерін зерттеңіз. DOM, оқиғалар, функциялар және қазіргі заманғы синтаксис арқылы динамикалық беттер жасауды қамтиды.',
    'course.javascript-for-beginners.summary': 'JavaScript-пен танысып, алғашқы динамикалық беттерді жасаңыз.',
    'course.javascript_for_beginners.title': 'JavaScript бастаушыларға',
    'course.javascript_for_beginners.description': 'Интерактивті веб-дамытуды үйрену үшін JavaScript негіздерін зерттеңіз. DOM, оқиғалар, функциялар және қазіргі заманғы синтаксис арқылы динамикалық беттер жасауды қамтиды.',
    'course.javascript_for_beginners.summary': 'JavaScript-пен танысып, алғашқы динамикалық беттерді жасаңыз.',
    'course.react-framework.title': 'React Framework',
    'course.react-framework.description': 'React көмегімен динамикалық пайдаланушы интерфейстерін жасаңыз. Курс сізді күйді басқаруға, қайта пайдалануға болатын компоненттерге және заманауи UI үлгілеріне бастайды.',
    'course.react-framework.summary': 'React-пен заманауи фронтенд қолданбаларын жасауды үйреніңіз.',
    'course.react_framework.title': 'React Framework',
    'course.react_framework.description': 'React көмегімен динамикалық пайдаланушы интерфейстерін жасаңыз. Курс сізді күйді басқаруға, қайта пайдалануға болатын компоненттерге және заманауи UI үлгілеріне бастайды.',
    'course.react_framework.summary': 'React-пен заманауи фронтенд қолданбаларын жасауды үйреніңіз.',
    'course.vue-js-framework.title': 'Vue JS Framework',
    'course.vue-js-framework.description': 'Vue.js прогрессивті фреймворкы арқылы заманауи веб-қосымшалар жасаңыз. Сіз реактивтілікті, компонент құрылымын және қолдау оңай SPA жасауды үйренесіз.',
    'course.vue-js-framework.summary': 'Vue.js-пен реактивті қосымшаларды оңай синтаксиспен жасаңыз.',
    'course.vuejs_framework.title': 'Vue JS Framework',
    'course.vuejs_framework.description': 'Vue.js прогрессивті фреймворкы арқылы заманауи веб-қосымшалар жасаңыз. Сіз реактивтілікті, компонент құрылымын және қолдау оңай SPA жасауды үйренесіз.',
    'course.vuejs_framework.summary': 'Vue.js-пен реактивті қосымшаларды оңай синтаксиспен жасаңыз.',
    'course.unity-development.title': 'Unity дамыту',
    'course.unity-development.description': 'Unity-де ойын әзірлеуді үйреніп, тартымды жобалар жасаңыз. Курс сахна жасау, скрипт жазу, физика және ойын процесін жобалау сияқты тақырыптарды қарастырады.',
    'course.unity-development.summary': 'Unity-де практикалық сабақтар арқылы ойын жасауды бастаңыз.',
    'course.unity_development.title': 'Unity дамыту',
    'course.unity_development.description': 'Unity-де ойын әзірлеуді үйреніп, тартымды жобалар жасаңыз. Курс сахна жасау, скрипт жазу, физика және ойын процесін жобалау сияқты тақырыптарды қарастырады.',
    'course.unity_development.summary': 'Unity-де практикалық сабақтар арқылы ойын жасауды бастаңыз.',
  }
};

export const useLanguageStore = defineStore('language', () => {
  const currentLanguage = ref<Language>('en');

  const initLanguage = () => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['en', 'ru', 'kk'].includes(savedLang)) {
      currentLanguage.value = savedLang;
    } else {
      // Default to English
      currentLanguage.value = 'en';
    }
  };

  const setLanguage = (lang: Language) => {
    currentLanguage.value = lang;
    localStorage.setItem('language', lang);
    document.documentElement.setAttribute('lang', lang);
  };

  const t = (key: string): string => {
    return translations[currentLanguage.value]?.[key] || key;
  };

  const tCourse = (key: string, fallback: string): string => {
    return translations[currentLanguage.value]?.[key] || fallback;
  };

  return {
    currentLanguage,
    initLanguage,
    setLanguage,
    t,
    tCourse
  };
});
