# Generated by Django 5.1.1 on 2024-10-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_delete_payment'),
        ('user_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
